name: 'Rebol CI'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.3.3

    - name: Build 64bit Rebol/Bulk using MSVC
      run: ./siskin.exe make/rebol3.nest [msvc %rebol3-bulk-x64-clang]

    - name: Prepare 64bit Rebol/Bulk for upload
      run: MOVE ./msvc/Release-x64/rebol3-bulk-x64-vs.exe ./rebol3-bulk-x64.exe

    - name: Build 64bit test extension using MSVC
      run: ./siskin.exe make/rebol3.nest [msvc %test-x64.rebx]

    - name: Prepare 64bit test extension
      run: MOVE ./msvc/Release-x64/test-x64.rebx.dll ./test-x64.rebx

    - name: Test 64bit Rebol/Bulk
      run: ./rebol3-bulk-x64.exe -s ./src/tests/run-tests.r3


    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v2
      with:
        name: Rebol-CI-${{github.run_id}}
        path: ./rebol3-*.exe

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.3.3

      - name: Build 64bit Rebol/Bulk using gcc
        run: ./siskin make/rebol3.nest %rebol3-bulk-x64-libc-gcc

      - name: Build 64bit test extension using gcc
        run: |
          ./siskin make/rebol3.nest %test-x64.rebx
          cp ./build/test-x64.rebx ./src/tests/
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/$PWD/src/tests/

      - name: Test 64bit Rebol/Bulk
        run: ./build/rebol3-bulk-x64-libc-gcc -s ./src/tests/run-tests.r3

      - name: Prepare 64bit Rebol/Bulk for upload
        run: |
          mv ./build/rebol3-bulk-x64-libc-gcc ./rebol3-bulk-x64-libc
          gzip -9 ./rebol3-bulk-x64-libc

      #- name: Build 64bit Rebol/Bulk using clang
      #  run: |
      #    ./siskin make/rebol3.nest %rebol3-bulk-x64-libc-clang
      #    mv ./build/rebol3-bulk-x64-libc-clang ./rebol3-bulk-x64-libc-clang
      #    gzip -9 ./rebol3-bulk-x64-libc-clang

      - uses: actions/upload-artifact@v2
        with:
          name: Rebol-CI-${{github.run_id}}
          path: ./rebol3-*.gz

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.3.3

      - name: Build 64bit Rebol/Bulk using clang
        run: ./siskin make/rebol3.nest %rebol3-bulk-x64-osx

      - name: Build 64bit test extension
        run: |
          ./siskin make/rebol3.nest %test-x64.rebx
          cp ./build/test-x64.rebx ./src/tests/

      - name: Test 64bit Rebol/Bulk
        run: ./build/rebol3-bulk-x64-osx -s ./src/tests/run-tests.r3

      - name: Prepare 64bit Rebol/Bulk for upload
        run: |
          mv ./build/rebol3-bulk-x64-osx ./rebol3-bulk-x64-osx
          gzip -9 ./rebol3-bulk-x64-osx

      - uses: actions/upload-artifact@v2
        with:
          name: Rebol-CI-${{github.run_id}}
          path: ./rebol3-*.gz
